services:
  - name: movie-downloader-backend
    type: web
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: CHROME_PATH
        value: /usr/bin/chromium  # Updated Chromium path
    disk:
      name: persistent-data
      size: 1GB
    healthCheckPath: /
    runtime:
      - nodejs: 16
    staticPublish:
      directory: public

    # Install Chromium and its dependencies, and confirm the installation
    installCommand: |
      apt-get update && apt-get install -y \
      fonts-liberation \
      libappindicator3-1 \
      libasound2 \
      libatk-bridge2.0-0 \
      libcups2 \
      libdbus-1-3 \
      libgbm-dev \
      libnspr4 \
      libnss3 \
      libx11-xcb1 \
      libxcomposite1 \
      libxdamage1 \
      libxrandr2 \
      xdg-utils \
      wget \
      libu2f-udev \
      && apt-get install -y chromium \
      && apt-get -f install -y \
      && which chromium && chromium --version  # Confirm installation and path
