services:
  - name: movie-downloader-backend
    type: web
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free # Use a free plan; change to a paid plan if needed
    region: oregon # Choose the closest region to your audience
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: persistent-data
      size: 1GB
    healthCheckPath: /
    runtime:
      - nodejs: 16 # Update the Node.js version to your requirement
    staticPublish:
      directory: public

    # Updated installCommand without manual installation of Chrome
    installCommand: |
      apt-get update && apt-get install -y \
      fonts-liberation \
      libappindicator3-1 \
      libasound2 \
      libatk-bridge2.0-0 \
      libcups2 \
      libdbus-1-3 \
      libgbm-dev \
      libnspr4 \
      libnss3 \
      libx11-xcb1 \
      libxcomposite1 \
      libxdamage1 \
      libxrandr2 \
      xdg-utils \
      wget \
      libu2f-udev

    # Puppeteer will automatically download Chromium during the npm install process
